services:
  # Local AWS emulator
#  localstack:
#    image: localstack/localstack:stable
#    container_name: device-localstack
#    environment:
#      - SERVICES=sqs                       # enable SQS only
#      - AWS_DEFAULT_REGION=us-east-1
#      - LS_LOG=info
#      - HOSTNAME_EXTERNAL=localstack       # make generated URLs resolve inside the Compose network
#    ports:
#      - "4566:4566"                        # edge port for all AWS services
#    volumes:
#      - localstack-data:/var/lib/localstack
#    healthcheck:
#      test: ["CMD", "bash", "-lc", "curl -sf http://localhost:4566/_localstack/health | grep '\"initialized\": true'"]
#      interval: 3s
#      timeout: 2s
#      retries: 20
#    networks:
#      - sky-comm
  redis:
    image: redis:7-alpine
    container_name: redis
#    ports:
#      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - sky-comm

  device-gateway:
    build:
      context: .
    container_name: device-gateway
    env_file: .env
    networks:
      - sky-comm

#volumes:
#  localstack-data:
networks:
  sky-comm:
    external: true
    driver: bridge