services:
  localstack:
    image: localstack/localstack:stable
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/var/lib/localstack
    healthcheck:
      test: [ "CMD-SHELL", "python -c \"import json,urllib.request,sys; d=json.load(urllib.request.urlopen('http://localhost:4566/_localstack/health')); sys.exit(0 if d.get('initialized') else 1)\"" ]
      interval: 5s
      timeout: 3s
      retries: 30


  sqs-init:
    image: amazon/aws-cli:2.15.40
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      AWS_DEFAULT_REGION: ${AWS_REGION:-us-east-1}
    entrypoint: ["/bin/sh","-lc"]
    command: >
      aws --endpoint-url http://localstack:4566 sqs create-queue
      --queue-name ${QUEUE_NAME:-device-messages} || true
    restart: "no"

  device-gateway:
    build: .
    depends_on:
      localstack:
        condition: service_healthy
      sqs-init:
        condition: service_completed_successfully
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      SQS_ENDPOINT_URL: ${SQS_ENDPOINT_URL:-http://localstack:4566}
      ACCOUNT_ID: ${ACCOUNT_ID:-000000000000}
      QUEUE_NAME: ${QUEUE_NAME:-device-messages}
      NUM_DEVICES: ${NUM_DEVICES:-3}
      SEND_INTERVAL_SEC: ${SEND_INTERVAL_SEC:-2}
    command: ["python", "main.py"]

volumes:
  localstack-data:
