version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"         # gateway for all services
    environment:
      - SERVICES=s3,sqs     # add whatever other services you may want to use
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
