services:
#  localstack:
#    image: localstack/localstack:stable
#    container_name: device-localstack
#    environment:
#      - SERVICES=sqs                       # enable SQS only
#      - AWS_DEFAULT_REGION=us-east-1
#      - LS_LOG=info
#      - HOSTNAME_EXTERNAL=localstack       # make generated URLs resolve inside the Compose network
#    ports:
#      - "4566:4566"                        # edge port for all AWS services
#    volumes:
#      - localstack-data:/var/lib/localstack
#    healthcheck:
#      test: ["CMD", "bash", "-lc", "curl -sf http://localhost:4566/_localstack/health | grep '\"initialized\": true'"]
#      interval: 3s
#      timeout: 2s
#      retries: 20
#    networks:
#      - sky-comm

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config/loki.yaml
    volumes:
      - ./loki/config/loki.yaml:/etc/loki/config/loki.yaml:ro
      - ./loki/data:/loki
    networks:
      - sky-comm

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    networks:
      - sky-comm

  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - sky-comm
  redis:
    image: redis:7-alpine
    container_name: redis
#    ports:
#      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - sky-comm

  device-gateway:
    build:
      context: .
    container_name: device-gateway
    env_file: .env
    networks:
      - sky-comm

#volumes:
#  localstack-data:
networks:
  sky-comm:
    external: true
    driver: bridge